config/routes.rb
Rails.application.routes.draw do
  resources :councils
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/council.rb
class Council < ApplicationRecord
end

app/models/ping.rb
class Ping < ApplicationRecord
  belongs_to :council
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/councils_controller.rb
class CouncilsController < ApplicationController
  before_action :set_council, only: [:show, :edit, :update, :destroy]

  # GET /councils
  # GET /councils.json
  def index
    @councils = Council.all
  end

  # GET /councils/1
  # GET /councils/1.json
  def show
  end

  # GET /councils/new
  def new
    @council = Council.new
  end

  # GET /councils/1/edit
  def edit
  end

  # POST /councils
  # POST /councils.json
  def create
    @council = Council.new(council_params)

    respond_to do |format|
      if @council.save
        format.html { redirect_to @council, notice: 'Council was successfully created.' }
        format.json { render :show, status: :created, location: @council }
      else
        format.html { render :new }
        format.json { render json: @council.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /councils/1
  # PATCH/PUT /councils/1.json
  def update
    respond_to do |format|
      if @council.update(council_params)
        format.html { redirect_to @council, notice: 'Council was successfully updated.' }
        format.json { render :show, status: :ok, location: @council }
      else
        format.html { render :edit }
        format.json { render json: @council.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /councils/1
  # DELETE /councils/1.json
  def destroy
    @council.destroy
    respond_to do |format|
      format.html { redirect_to councils_url, notice: 'Council was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_council
      @council = Council.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def council_params
      params.require(:council).permit(:gss, :name, :url, :snac, :ideal_postcodes_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/councils_helper.rb
module CouncilsHelper
end

app/views/councils/_form.html.erb
<%= form_with(model: council, local: true) do |form| %>
  <% if council.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(council.errors.count, "error") %> prohibited this council from being saved:</h2>

      <ul>
      <% council.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :gss %>
    <%= form.text_field :gss %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :snac %>
    <%= form.text_field :snac %>
  </div>

  <div class="field">
    <%= form.label :ideal_postcodes_name %>
    <%= form.text_field :ideal_postcodes_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/councils/edit.html.erb
<h1>Editing Council</h1>

<%= render 'form', council: @council %>

<%= link_to 'Show', @council %> |
<%= link_to 'Back', councils_path %>

app/views/councils/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Councils</h1>

<table>
  <thead>
    <tr>
      <th>Gss</th>
      <th>Name</th>
      <th>Url</th>
      <th>Snac</th>
      <th>Ideal postcodes name</th>
      <th>lad18nm</th>
      <th>fid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @councils.each do |council| %>
      <tr class="<%= council.is_online ? 'online' : 'offline' %>">
        <td><%= council.gss %></td>
        <td><%= council.name %></td>
        <td><%= council.url %></td>
        <td><%= council.snac %></td>
        <td><%= council.ideal_postcodes_name %></td>
        <td><%= council.lad18nm %></td>
        <td><%= council.fid %></td>
        <td><%= link_to 'Show', council %></td>
        <td><%= link_to 'Edit', edit_council_path(council) %></td>
        <td><%= link_to 'Destroy', council, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Council', new_council_path %>

app/views/councils/new.html.erb
<h1>New Council</h1>

<%= render 'form', council: @council %>

<%= link_to 'Back', councils_path %>

app/views/councils/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gss:</strong>
  <%= @council.gss %>
</p>

<p>
  <strong>Name:</strong>
  <%= @council.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @council.url %>
</p>

<p>
  <strong>Snac:</strong>
  <%= @council.snac %>
</p>

<p>
  <strong>Ideal postcodes name:</strong>
  <%= @council.ideal_postcodes_name %>
</p>

<%= link_to 'Edit', edit_council_path(@council) %> |
<%= link_to 'Back', councils_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CouncilApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>